name: Build and test

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4
          target: esp32
          path: '.'
      - name: Wokwi CI Server
        uses: wokwi/wokwi-ci-server-action@v1
      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          expect_text: 'any webserver online'
      - name: CI Server Logs
        if: always()
        run: |
          docker logs -t $(docker ps -q)
